language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp 
after_success:
- npm run-script coveralls
deploy:
  provider: npm
  email: alex.titarenko@live.com
  api_key:
    secure: hlx4NOA6L9g34TNL8+hPaRZ45QKkffGbcwmIdffJ9cuRoL4i+XOYox+MwEgtWHZ8EuNNjhfBB+Pg2C1rCotem4NRsW8G6mjuHYrpgVb0eKJn1QyxEEfW+XYbi5y0+Q4s6VV3pMgCz7scVTT9GHu1vZElkGX3SalJYI3LrqxX5Mg+s5RTjEdMoXa6Cb3Ixv+oR1ZBylP/rMpgytAiPIB4ju4pHxXDNscQYayamslLpYAAR4EJaHHIEYYguaEPFZCCD3FJqeihCy9bExz8gy79Ht34/OcfxBbDwY4EmMatXlrBF87fHO6/rN3QbCy30PBflA/IOoeTRnk5GIHjxMcnWSUvFUvEVw7zCbOeqB9cLQ+fsj1JOZzWrri/I4crOQkt/kMUClp0qbUrT7EkovihYELoFBxUGUISXUgs4oA5d8gDyvhPesrAxtliZISV5FmsanxCsz0egwjxlr2ku5nbAcf4azI6Jj1vXAzDN/uh3qH6XR15cvi34w1ZQdNB2NOBT1pawm+Qi7HLHpTuqm79TgqX2hrZHbwUVMfzmkqF1hmOTuPMmV8iRRDpMlamIbObkVnhUZK3kDoxneONdiclOHPVMM0OIqMysW9faYVjcDD0cPxkpaVoYX/urQMCYXfeVAJ+QTYJwC68cWKd0Mklyn+j6vo0FJNn3AoTTTygAKI=
